announcement
PasteUs/PasteMeFrontend pull request #196
Opened 2020-02-15 09:23 UTC by fishTwelve

2020-02-15 10:39 UTC, LucienShui requested changes

2020-02-15 10:39 UTC, LucienShui commented on src/assets/lang/en.js
> +        more: 'more',
`m` 大写。

2020-02-15 10:39 UTC, LucienShui commented on public/usr/config.example.json
> +  "adminApi": "/_api/admin/api/",
`adminApi` 默认置为空串。

2020-02-16 03:54 UTC, LucienShui approved these changes

2020-02-16 05:31 UTC, ryanlee2014 approved these changes
没啥问题，注意eslint的提示，除了某些方便测试的地方可以用eslint-disable,其他建议按照eslint提示，并思考其中原因。

另外可以搞一下TypeScript( 
可以标记DTO，用decorator(
以及
> 动态一时爽，重构火葬场


> 

>

2020-02-16 05:31 UTC, ryanlee2014 commented on src/assets/js/highlightjs-line-numbers.js
> +        // eslint-disable-next-line no-prototype-builtins
这个可以改成:
```javascript
Object.prototype.hasOwnProperty.call(nodes, node)
```
目的是nodes的原型链的`hasOwnProperty`可能被污染，因此使用Object原型链上的方法

2020-02-16 06:03 UTC, LucienShui approved these changes

2020-02-20 03:11 UTC, merged